### ISSUE TITLE
Heap removeAt function

### ISSUE THREAD

**Issue by alexbredy** [raywenderlich/swift-algorithm-club#478] opened 2017-05-27 11:49 UTC
### Category

- [x] Question

### Brief Intro

Question regarding the way the function removeAt is executed

### More Details

```swift
public mutating func removeAt(_ index: Int) -> T? {
    guard index < elements.count else { return nil }

    let size = elements.count - 1
    if index != size {
      swap(&elements[index], &elements[size])
      shiftDown(index, heapSize: size)
      shiftUp(index)
    }
    return elements.removeLast()
}
```

Since we're shifting down the newly added element and we're therefore reordering the array, is there not a risk that elements.removeLast() does not remove the value we originally wanted to delete?
Should we not remove the last element before running the shift functions? 

Thanking you in advance for your help.

**Comment by vincentngo** [comment] 2017-10-07 05:30
@alexbredy you are right, there is a potential for the element you are removing to be shifted before! Good catch! We should just delete the element after we swap it before performing the shift operations. Do you want to submit a PR for this?

**Comment by mnespor** [comment] 2017-10-07 22:00
I tried to come up with a failing test and couldn't. I think `shiftUp(index:)` can only affect elements with index not greater than `index`, and `shiftDown(index:heapSize:)` can only affect elements with index not greater than `heapSize`? Here, `elements.count - 1` is passed as `heapSize`, which seems to leave the last element untouched always.

**Comment by vincentngo** [comment] 2017-10-08 22:37
@mnespor take a look at this example. Let say we remove at index 0. 

<img width="431" alt="screen shot 2017-10-08 at 6 33 47 pm" src="https://user-images.githubusercontent.com/1634736/31321669-3fa647f4-ac57-11e7-9e9f-0b306638f81c.png">

So we swap root element with the last. 

Perform the shift downs. You will notice that 10 is swapped with 5. Removing the last element will return 5. 

So in this case it breaks.

<img width="453" alt="screen shot 2017-10-08 at 6 36 27 pm" src="https://user-images.githubusercontent.com/1634736/31321699-bd777892-ac57-11e7-8b61-d304670dd5bf.png">


Correct me if im wrong.

**Comment by mnespor** [comment] 2017-10-09 01:06
I think the key is the argument passed to `shiftDown()`. In the first test, I've made a modified version of `removeAt()` here that calls `shiftDown()` with `h.elements.count` instead of `h.elements.count - 1` and it behaves like your example:

![image](https://user-images.githubusercontent.com/725618/31322797-9e5790b2-ac63-11e7-83d2-c91e0093f1c4.png)

The existing `removeAt()` implementation gets 10 though.

**Comment by vincentngo** [comment] 2017-10-09 01:58
@mnespor Sounds good, thanks for creating these test cases! Makes sense! I'll be closing this issue since it's not a bug.

**Closed by vincentngo** 2017-10-09 01:58 UTC
Labels: bug, hacktoberfest
